project:
  name: Logistic Pack Facade
  debug: true
  environment: development

kafka:
  tick: 4s
  topics: 
    - "created"
    - "removed"
    - "updated"
  groupId: "logistic-pack"
  brokers:
    - "kafka:9092"
    # - "localhost:9094" # for local launch
